/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.12                          *
*        Compiled Jun 29 2011, 15:28:47                              *
*        (c) 2011 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "DIALOG.h"

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/

#define ID_FRAMEWIN_0 (GUI_ID_USER + 0x00)
#define ID_SLIDER_0 (GUI_ID_USER + 0x01)
#define ID_BUTTON_0 (GUI_ID_USER + 0x02)
#define ID_TEXT_0 (GUI_ID_USER + 0x03)
#define ID_TEXT_1 (GUI_ID_USER + 0x04)
#define ID_EDIT_0 (GUI_ID_USER + 0x05)
#define ID_TEXT_2 (GUI_ID_USER + 0x06)
#define ID_RADIO_0 (GUI_ID_USER + 0x07)
#define ID_CHECKBOX_0 (GUI_ID_USER + 0x08)
#define ID_CHECKBOX_1 (GUI_ID_USER + 0x09)
#define ID_CHECKBOX_2 (GUI_ID_USER + 0x0A)
#define ID_CHECKBOX_3 (GUI_ID_USER + 0x0B)
#define ID_DROPDOWN_0 (GUI_ID_USER + 0x0C)
#define ID_DROPDOWN_1 (GUI_ID_USER + 0x0D)
#define ID_PROGBAR_0 (GUI_ID_USER + 0x0E)

// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { FRAMEWIN_CreateIndirect, "App", ID_FRAMEWIN_0, 0, 0, 800, 480, 0, 0, 0 },
  { SLIDER_CreateIndirect, "Slider", ID_SLIDER_0, 80, 140, 240, 25, 0, 0, 0 },
  { BUTTON_CreateIndirect, "Button", ID_BUTTON_0, 167, 186, 80, 20, 0, 0, 0 },
  { TEXT_CreateIndirect, "0", ID_TEXT_0, 90, 119, 50, 20, 0, 0, 0 },
  { TEXT_CreateIndirect, "100", ID_TEXT_1, 311, 119, 50, 20, 0, 0, 0 },
  { EDIT_CreateIndirect, "SliderValue", ID_EDIT_0, 347, 143, 80, 20, 0, 100, 0 },
  { TEXT_CreateIndirect, "Value", ID_TEXT_2, 349, 122, 80, 20, 0, 0, 0 },
  { RADIO_CreateIndirect, "Radio", ID_RADIO_0, 90, 250, 100, 150, 0, 7685, 0 },
  { CHECKBOX_CreateIndirect, "Checkbox", ID_CHECKBOX_0, 250, 250, 80, 20, 0, 0, 0 },
  { CHECKBOX_CreateIndirect, "Checkbox", ID_CHECKBOX_1, 250, 310, 80, 20, 0, 0, 0 },
  { CHECKBOX_CreateIndirect, "Checkbox", ID_CHECKBOX_2, 250, 340, 80, 20, 0, 0, 0 },
  { CHECKBOX_CreateIndirect, "Checkbox", ID_CHECKBOX_3, 250, 280, 80, 20, 0, 0, 0 },
  { DROPDOWN_CreateIndirect, "Dropdown", ID_DROPDOWN_0, 400, 300, 80, 80, 0, 0, 0 },
  { DROPDOWN_CreateIndirect, "Dropdown", ID_DROPDOWN_1, 500, 300, 80, 80, 0, 0, 0 },
  { PROGBAR_CreateIndirect, "Progbar", ID_PROGBAR_0, 80, 50, 240, 30, 0, 0, 0 },
  // USER START (Optionally insert additional widgets)
  
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN hItem,hDlg;
  WM_HWIN hItem1;
  int Id, NCode;
  // USER START (Optionally insert additional variables)
  hDlg = pMsg->hWin;
  // USER END

  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
    //
    // Initialization of 'Button'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0);
    BUTTON_SetText(hItem, "Increase");
    //
    // Initialization of 'Radio'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_RADIO_0);
    RADIO_SetText(hItem, "Black", 0);
    RADIO_SetText(hItem, "Yellow", 1);
    RADIO_SetText(hItem, "Green", 2);
    RADIO_SetText(hItem, "Blue", 3);
    RADIO_SetText(hItem, "Red", 4);
    //
    // Initialization of 'Checkbox'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_0);
    CHECKBOX_SetText(hItem, "Temperature");
    //
    // Initialization of 'Checkbox'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_1);
    CHECKBOX_SetText(hItem, "Pressure");
    //
    // Initialization of 'Checkbox'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_2);
    CHECKBOX_SetText(hItem, "Volume");
    //
    // Initialization of 'Checkbox'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_3);
    CHECKBOX_SetText(hItem, "Area");
    //
    // Initialization of 'Dropdown'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_DROPDOWN_0);
    DROPDOWN_AddString(hItem, "C Eqv");
    DROPDOWN_AddString(hItem, "Si");
    DROPDOWN_AddString(hItem, "C");
    //
    // Initialization of 'Dropdown'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_DROPDOWN_1);
    DROPDOWN_AddString(hItem, "CUP1");
    DROPDOWN_AddString(hItem, "CUP2");
    DROPDOWN_AddString(hItem, "CUP3");
    DROPDOWN_AddString(hItem, "CUP4");
    // USER START (Optionally insert additional code for further widget initialization)
    // USER END
    break;
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_SLIDER_0: // Notifications sent by 'Slider'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)

        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_0: // Notifications sent by 'Button'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
		  hItem = WM_GetDialogItem(hDlg, ID_SLIDER_0);
		  int val = SLIDER_GetValue(hItem);
		  if (val >= 100) val = -5;
		  val += 5;
		  SLIDER_SetValue(hItem, val);
		  hItem = WM_GetDialogItem(hDlg, ID_EDIT_0);
		  EDIT_SetValue(hItem, val);
		  hItem = WM_GetDialogItem(hDlg, ID_PROGBAR_0);
		  PROGBAR_SetValue(hItem, val);
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_EDIT_0: // Notifications sent by 'SliderValue'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
		  
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_RADIO_0: // Notifications sent by 'Radio'
		switch (NCode) {
		case WM_NOTIFICATION_CLICKED:
			// USER START (Optionally insert code for reacting on notification message)
			hItem = WM_GetDialogItem(hDlg, ID_RADIO_0);
			int color = RADIO_GetValue(hItem);
			hItem1 = WM_GetDialogItem(hDlg, ID_PROGBAR_0);
			switch (color) {

			case 0:
				PROGBAR_SetBarColor(hItem1, 0, GUI_BLACK);
				break;
			case 1:
				PROGBAR_SetBarColor(hItem1, 0, GUI_YELLOW);
				break;
			case 2:
				PROGBAR_SetBarColor(hItem1, 0, GUI_GREEN);
				break;
			case 3:
				PROGBAR_SetBarColor(hItem1, 0, GUI_BLUE);
				break;
			case 4:
				PROGBAR_SetBarColor(hItem1, 0, GUI_RED);
				break;
			}
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_CHECKBOX_0: // Notifications sent by 'Checkbox'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
		 
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_CHECKBOX_1: // Notifications sent by 'Checkbox'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
		 
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_CHECKBOX_2: // Notifications sent by 'Checkbox'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
		 
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_CHECKBOX_3: // Notifications sent by 'Checkbox'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
		
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_DROPDOWN_0: // Notifications sent by 'Dropdown'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_SEL_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_DROPDOWN_1: // Notifications sent by 'Dropdown'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_SEL_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    // USER START (Optionally insert additional code for further Ids)
    // USER END
    }
    break;
  // USER START (Optionally insert additional message handling)
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateApp
*/
WM_HWIN CreateApp(void);
WM_HWIN CreateApp(void) {
	WM_HWIN hWin, hItem;
	  FRAMEWIN_Handle hTest;
	  FRAMEWIN_SetDefaultTextAlign( GUI_TA_HCENTER);
	  FRAMEWIN_SetDefaultClientColor(GUI_LIGHTMAGENTA);

  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), &_cbDialog, WM_HBKWIN, 0, 0);
  //hTest = (FRAMEWIN_Handle)WM_GetDialogItem(hWin, ID_FRAMEWIN_0);

 // FRAMEWIN_SetTextAlign(hTest, GUI_TA_HCENTER);
	//  FRAMEWIN_SetClientColor(hTest,GUI_LIGHTMAGENTA);
  hItem = WM_GetDialogItem(hWin, ID_EDIT_0);
  EDIT_SetDecMode(hItem, 0, 0, 100, 0, GUI_EDIT_SUPPRESS_LEADING_ZEROES);
  EDIT_SetValue(hItem, 0);

  hItem = WM_GetDialogItem(hWin, ID_SLIDER_0);
  SLIDER_SetNumTicks(hItem, 20);

  return hWin;
}

// USER START (Optionally insert additional public code)
void MainTask(void);
void MainTask(void) {
	GUI_Init();
	
	CreateApp();
	while (1) {
		GUI_Delay(200);
	}
}
// USER END

/*************************** End of file ****************************/
